import 'package:flutter/material.dart';

class AppColors {
  // Premium Color Palette
  static const Color primary = Color(0xFF8B5CF6); // Violet
  static const Color primaryDark = Color(0xFF7C3AED);
  static const Color secondary = Color(0xFF10B981); // Emerald
  static const Color accent = Color(0xFFF59E0B); // Amber
  
  static const Color background = Color(0xFFF8FAFC);
  static const Color surface = Colors.white;
  static const Color error = Color(0xFFEF4444);
  
  static const Color textPrimary = Color(0xFF1E293B);
  static const Color textSecondary = Color(0xFF64748B);
  
  // Gradients
  static const LinearGradient primaryGradient = LinearGradient(
    colors: [primary, Color(0xFFA78BFA)],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );
}

class AppStrings {
  static String get(BuildContext? context, String key, {String? langCode}) {
    // If langCode is provided, use it. Otherwise try to get it from context.
    String locale = langCode ?? 'ar';
    
    if (langCode == null && context != null) {
      try {
        locale = Localizations.localeOf(context).languageCode;
      } catch (_) {
        // Fallback to provider if available or default to Arabic
        locale = 'ar';
      }
    }
    
    return _translations[locale]?[key] ?? _translations['ar']?[key] ?? key;
  }

  static String parseMessage(BuildContext context, String message) {
    if (!message.contains('|')) {
      return get(context, message);
    }
    final parts = message.split('|');
    final key = parts[0];
    String translated = get(context, key);

    if (key == 'error_msg' || key == 'excel_read_error') {
      translated = translated.replaceFirst('{error}', parts[1]);
    } else if (key == 'excel_import_success') {
      translated = translated.replaceFirst('{count}', parts[1]);
    } else if (key == 'excel_import_pending') {
      translated = translated.replaceFirst('{count}', parts[1]);
      translated = translated.replaceFirst('{pending}', parts[2]);
    }
    
    return translated;
  }

  static const Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_title': 'عطور الفخامة',
      'login': 'تسجيل الدخول',
      'owner_login': 'تسجيل دخول صاحب العمل',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'remember_me': 'تذكرني',
      'login_google': 'المتابعة باستخدام حساب Google',
      'enter_email': 'أدخل البريد الإلكتروني',
      'invalid_email': 'صيغة البريد غير صحيحة',
      'enter_password': 'أدخل كلمة المرور',
      'password_short': 'كلمة المرور قصيرة',
      'welcome': 'مرحباً بك في عالم الفخامة',
      'products': 'المنتجات',
      'all': 'الكل',
      'my_orders': 'طلباتي',
      'profile': 'الملف الشخصي',
      'add_to_cart': 'إضافة للسلة',
      'added_to_cart': 'تم إضافة {name} للسلة',
      'out_of_stock': 'نفذ من المخزون',
      'price': 'السعر',
      'currency': 'ر.س',
      'language': 'اللغة',
      'change_language': 'تغيير اللغة',
      'dashboard': 'لوحة التحكم',
      'logout': 'تسجيل الخروج',
      'hello': 'مرحباً',
      'owner': 'صاحب العمل',
      'quick_actions': 'الإجراءات السريعة',
      'manage_products': 'إدارة المنتجات',
      'add_edit_delete': 'إضافة، تعديل، حذف',
      'registered_products': 'منتج مسجّل',
      'uploaded_firebase': 'مرفوع على Firebase',
      'pending_sync': 'في انتظار الاتصال',
      'synced_local': 'قاعدة بيانات محلية مزامنة',
      'orders': 'الطلبات',
      'manage_orders': 'إدارة طلبات العملاء',
      'search_hint': 'ابحث عن عطر أو ماركة...',
      'discover_luxury': 'اكتشف أفخر العطور العالمية',
      'cart': 'السلة',
      'no_results': 'لا توجد نتائج',
      'remaining': 'المتبقي',
      'my_account': 'حسابي',
      'cart_and_order': 'سلة المشتريات والطلب',
      'login_required_order': 'يجب تسجيل الدخول لإتمام عملية الطلب وتتبع مشترياتك',
      'login_create_account': 'تسجيل الدخول / إنشاء حساب',
      'cart_empty': 'السلة فارغة',
      'total': 'المجموع',
      'grand_total': 'الإجمالي',
      'delivery_info': 'بيانات التوصيل',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'delivery_address': 'عنوان التوصيل',
      'additional_notes': 'ملاحظات إضافية (اختياري)',
      'confirm_order': 'تأكيد الطلب',
      'required_field': 'مطلوب',
      'order_submitted': 'تم إرسال الطلب',
      'login_required_profile': 'يجب تسجيل الدخول لمشاهدة طلباتك',
      'no_name': 'بدون اسم',
      'previous_orders': 'طلباتي السابقة',
      'no_previous_orders': 'لا توجد طلبات سابقة',
      'order_id': 'طلب #',
      'date': 'التاريخ',
      'items_count': 'المنتجات ({count}):',
      'status_pending': 'قيد الانتظار',
      'status_accepted': 'مقبول',
      'status_cancelled': 'ملغى',
      'invoice_generation_failed': 'فشل إنشاء الفاتورة',
      'save_invoice': 'حفظ الفاتورة',
      'invoice_saved_success': 'تم حفظ الفاتورة بنجاح في:\n{path}',
      'save_error': 'حدث خطأ أثناء الحفظ: {error}',
      'manage_orders_title': 'إدارة الطلبات',
      'no_orders_currently': 'لا توجد طلبات حالياً',
      'customer': 'العميل',
      'notes_label': 'ملاحظات',
      'print_invoice': 'طباعة الفاتورة',
      'accept': 'قبول',
      'cancel': 'إلغاء',
      'import_excel': 'استيراد من Excel',
      'pending_sync_count': '{count} منتج في انتظار الاتصال',
      'no_products_yet': 'لا توجد منتجات بعد',
      'add_product_hint': 'اضغط + لإضافة منتج أو استورد من Excel',
      'add_product': 'إضافة منتج',
      'add_new_product': 'إضافة منتج جديد',
      'perfume_name': 'اسم العطر',
      'brand_label': 'الماركة',
      'price_with_currency': 'السعر ({currency})',
      'size_hint': 'الحجم (مثل: 100ml)',
      'stock_quantity': 'الكمية في المخزون',
      'description_label': 'الوصف',
      'category_label': 'الفئة',
      'men': 'رجالي',
      'women': 'نسائي',
      'unisex': 'مختلط',
      'delete_product': 'حذف المنتج',
      'confirm_delete_msg': 'هل تريد حذف "{name}"؟',
      'delete_label': 'حذف',
      'stock_label': 'مخزون',
      'edit_label': 'تعديل',
      'customer_login_title': 'تسجيل الدخول للعملاء',
      'welcome_back': 'أهلاً بك مجدداً',
      'no_account_yet': 'ليس لديك حساب؟ إنشاء حساب جديد',
      'register_title': 'إنشاء حساب جديد',
      'create_account': 'إنشاء حساب',
      'already_have_account': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'password_too_short': 'يجب أن لا تقل عن 6 أحرف',
      'edit_product_title': 'تعديل المنتج',
      'saving': 'جارٍ الحفظ...',
      'save_changes': 'حفظ التعديلات',
      'changes_saved_success': 'تم حفظ التعديلات ✓',
      'order_accepted_msg': 'تم قبول الطلب ✓',
      'error_msg': 'خطأ: {error}',
      'order_cancelled_msg': 'تم إلغاء الطلب وإرجاع المخزون',
      'order_deleted_msg': 'تم حذف الطلب',
      'product_added_firebase': 'تمت الإضافة وتم رفعه على Firebase ✓',
      'product_added_local': 'تم الحفظ محلياً ⚠️ سيُرفع عند الاتصال بالإنترنت',
      'product_updated_success': 'تم التحديث بنجاح ✓',
      'product_updated_local': 'تم الحفظ محلياً ⚠️ سيُحدَّث عند الاتصال',
      'product_deleted_success': 'تم الحذف بنجاح ✓',
      'product_deleted_local': 'تم الحذف محلياً ⚠️',
      'excel_import_success': 'تم استيراد {count} منتج على Firebase ✓',
      'excel_import_pending': 'تم استيراد {count} منتج ({pending} في انتظار الاتصال) ⚠️',
      'excel_read_error': 'خطأ في قراءة Excel: {error}',
      'user_not_found': 'البريد الإلكتروني غير مسجل',
      'wrong_password': 'كلمة المرور غير صحيحة',
      'email_already_in_use': 'البريد الإلكتروني مستخدم مسبقاً',
      'weak_password': 'كلمة المرور ضعيفة جداً',
      'invalid_credential': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'generic_error': 'حدث خطأ، حاول مرة أخرى',
      'invoice_sheet_name': 'الفاتورة',
      'invoice_title': 'فاتورة طلب - عطور الفخامة',
      'invoice_order_id': 'رقم الطلب:',
      'invoice_date': 'التاريخ:',
      'invoice_customer_name': 'اسم العميل:',
      'invoice_customer_phone': 'رقم الهاتف:',
      'invoice_address': 'العنوان:',
      'invoice_serial': 'م',
      'invoice_product_name': 'اسم العطر',
      'invoice_quantity': 'الكمية',
      'invoice_price_sar': 'السعر (ر.س)',
      'invoice_total': 'الإجمالي',
      'invoice_grand_total': 'المجموع الكلي:',
      'init_error': 'خطأ في التهيئة:',
    },
    'en': {
      'app_title': 'Luxury Perfumes',
      'login': 'Login',
      'owner_login': 'Owner Login',
      'email': 'Email Address',
      'password': 'Password',
      'remember_me': 'Remember Me',
      'login_google': 'Continue with Google',
      'enter_email': 'Enter email address',
      'invalid_email': 'Invalid email format',
      'enter_password': 'Enter password',
      'password_short': 'Password is too short',
      'welcome': 'Welcome to the world of luxury',
      'products': 'Products',
      'all': 'All',
      'my_orders': 'My Orders',
      'profile': 'Profile',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'Added {name} to cart',
      'out_of_stock': 'Out of Stock',
      'price': 'Price',
      'currency': 'SAR',
      'language': 'Language',
      'change_language': 'Change Language',
      'dashboard': 'Dashboard',
      'logout': 'Logout',
      'hello': 'Hello',
      'owner': 'Owner',
      'quick_actions': 'Quick Actions',
      'manage_products': 'Manage Products',
      'add_edit_delete': 'Add, Edit, Delete',
      'registered_products': 'Registered Products',
      'uploaded_firebase': 'Uploaded to Firebase',
      'pending_sync': 'Waiting for sync',
      'synced_local': 'Local DB Synced',
      'orders': 'Orders',
      'manage_orders': 'Manage Customer Orders',
      'search_hint': 'Search for perfume or brand...',
      'discover_luxury': 'Discover the world\'s finest perfumes',
      'cart': 'Cart',
      'no_results': 'No results found',
      'remaining': 'Remaining',
      'my_account': 'My Account',
      'cart_and_order': 'Cart & Checkout',
      'login_required_order': 'Login required to complete your order',
      'login_create_account': 'Login / Create Account',
      'cart_empty': 'Your cart is empty',
      'total': 'Total',
      'grand_total': 'Grand Total',
      'delivery_info': 'Delivery Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'delivery_address': 'Delivery Address',
      'additional_notes': 'Additional Notes (Optional)',
      'confirm_order': 'Confirm Order',
      'required_field': 'Required',
      'order_submitted': 'Order submitted successfully',
      'login_required_profile': 'Login required to view your orders',
      'no_name': 'No name',
      'previous_orders': 'Previous Orders',
      'no_previous_orders': 'No previous orders',
      'order_id': 'Order #',
      'date': 'Date',
      'items_count': 'Items ({count}):',
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_cancelled': 'Cancelled',
      'invoice_generation_failed': 'Invoice generation failed',
      'save_invoice': 'Save Invoice',
      'invoice_saved_success': 'Invoice saved successfully at:\n{path}',
      'save_error': 'An error occurred while saving: {error}',
      'manage_orders_title': 'Manage Orders',
      'no_orders_currently': 'No orders currently',
      'customer': 'Customer',
      'notes_label': 'Notes',
      'print_invoice': 'Print Invoice',
      'accept': 'Accept',
      'cancel': 'Cancel',
      'import_excel': 'Import from Excel',
      'pending_sync_count': '{count} products waiting for sync',
      'no_products_yet': 'No products yet',
      'add_product_hint': 'Press + to add a product or import from Excel',
      'add_product': 'Add Product',
      'add_new_product': 'Add New Product',
      'perfume_name': 'Perfume Name',
      'brand_label': 'Brand',
      'price_with_currency': 'Price ({currency})',
      'size_hint': 'Size (e.g., 100ml)',
      'stock_quantity': 'Stock Quantity',
      'description_label': 'Description',
      'category_label': 'Category',
      'men': 'Men',
      'women': 'Women',
      'unisex': 'Unisex',
      'delete_product': 'Delete Product',
      'confirm_delete_msg': 'Do you want to delete "{name}"?',
      'delete_label': 'Delete',
      'stock_label': 'Stock',
      'edit_label': 'Edit',
      'customer_login_title': 'Customer Login',
      'welcome_back': 'Welcome Back',
      'no_account_yet': 'No account? Create new account',
      'register_title': 'Create New Account',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account? Login',
      'password_too_short': 'Must be at least 6 characters',
      'edit_product_title': 'Edit Product',
      'saving': 'Saving...',
      'save_changes': 'Save Changes',
      'changes_saved_success': 'Changes saved successfully ✓',
      'order_accepted_msg': 'Order accepted ✓',
      'error_msg': 'Error: {error}',
      'order_cancelled_msg': 'Order cancelled and stock returned',
      'order_deleted_msg': 'Order deleted',
      'product_added_firebase': 'Product added and uploaded to Firebase ✓',
      'product_added_local': 'Saved locally ⚠️ Will sync when online',
      'product_updated_success': 'Updated successfully ✓',
      'product_updated_local': 'Saved locally ⚠️ Will update when online',
      'product_deleted_success': 'Deleted successfully ✓',
      'product_deleted_local': 'Deleted locally ⚠️',
      'excel_import_success': 'Imported {count} products to Firebase ✓',
      'excel_import_pending': 'Imported {count} products ({pending} waiting for sync) ⚠️',
      'excel_read_error': 'Excel read error: {error}',
      'user_not_found': 'Email not registered',
      'wrong_password': 'Incorrect password',
      'email_already_in_use': 'Email already in use',
      'weak_password': 'Password is too weak',
      'invalid_credential': 'Invalid email or password',
      'generic_error': 'An error occurred, please try again',
      'invoice_sheet_name': 'Invoice',
      'invoice_title': 'Order Invoice - Luxury Perfumes',
      'invoice_order_id': 'Order ID:',
      'invoice_date': 'Date:',
      'invoice_customer_name': 'Customer Name:',
      'invoice_customer_phone': 'Phone Number:',
      'invoice_address': 'Address:',
      'invoice_serial': '#',
      'invoice_product_name': 'Perfume Name',
      'invoice_quantity': 'Qty',
      'invoice_price_sar': 'Price (SAR)',
      'invoice_total': 'Total',
      'invoice_grand_total': 'Grand Total:',
      'init_error': 'Initialization Error:',
    },
  };
}
