// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADr7E0uH0dFtZehNFY_gLIyjnooAHjz5c',
    appId: '1:128189556690:web:b49afe58967d9b150b4a0b',
    messagingSenderId: '128189556690',
    projectId: 'perfumes-eb0e9',
    authDomain: 'perfumes-eb0e9.firebaseapp.com',
    storageBucket: 'perfumes-eb0e9.firebasestorage.app',
    measurementId: 'G-MP94F1DE1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3CZLtwc_C5BE0U8htRoa6X948Y6Xc_Y',
    appId: '1:128189556690:android:8fdcb9f1a5685f240b4a0b',
    messagingSenderId: '128189556690',
    projectId: 'perfumes-eb0e9',
    storageBucket: 'perfumes-eb0e9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADr7E0uH0dFtZehNFY_gLIyjnooAHjz5c',
    appId: '1:128189556690:web:c966fa47aa8e56540b4a0b',
    messagingSenderId: '128189556690',
    projectId: 'perfumes-eb0e9',
    authDomain: 'perfumes-eb0e9.firebaseapp.com',
    storageBucket: 'perfumes-eb0e9.firebasestorage.app',
    measurementId: 'G-ZGXHXJLJQ4',
  );
}
